### PR TITLE
Add Format Check in GH Action

### PR DESCRIPTION
**Pull request by sundaram123krishnan**
Thought of adding a format checker in GH Action

### CODE REVIEW

**Review by andrewdavidmackenzie — COMMENTED** [review]
How long does the additional checkout and the format check take?

Just those two files with changes?
(Probably a PR of mine from Pi/vs code...)

**Comment by sundaram123krishnan** [comment]
After adding the format check:
image
~1min more it takes, not much difference

**Comment by andrewdavidmackenzie** [comment]
It says 3s, no?

**Comment by sundaram123krishnan** [comment]
Updated comment 
Overall time taken i mean

**Review by andrewdavidmackenzie — APPROVED** [review]

**Pull request merged**
