### PR TITLE
Add Popup Menu to Hardware Button in Info Row

### LINKED ISSUE #221: Make hardware button (in info_row) a pup-up menu
In order to add networking options, without cluttering the UI, I would like to make the current hardware_button in the info_bar at the bottom, pop-up a set of info, some options and a menu - similar to how some IDEs do it.

Here is an example from RustRover:
Screenshot 2024-07-02 at 7 44 15 PM

You click the UTF-8 encoding button and it pops up a menu, with some items other selections and a sub-menu.

I would like the hardware button to pop-up similarly and have this content:
- A selection to "Use local Pi hardware". This should be greyed out if the "pi_hw" feature is not used (I will change hw module to expose get() methods for pi_hw and for fake_hw)
- A selection "Connect to remote Pi" that should be greyed out if the "network" feature is not enabled. WHen clicked, this will open a dialog for connection parameters (need a separate issue for that)
- A selection "Search for Pis on local network" (TODO, so greyed out initially). This would open a dialog while search is done when working.
- A selection "Show hardware details" if hardware_description is not None. This would pop-up the existing Toast as we currently do when the current hardware_button is clicked.

If the hardware-button is clicked again, the pop-up menu should hide. Any open dialog should remain open.

Something as visually crafted as that example would be great, but "aspirational"! :-) 

This relates to #214 and will be needed to complete it.

### PR DESCRIPTION
**Pull request by sundaram123krishnan**
Fixes #221

### CODE REVIEW

**Comment by andrewdavidmackenzie** [comment]
Looking good, the only thing I can see to fix so far is:
- have the button text be (as now) the model name of the currently connected Hardware. So, e.g. "Fake Hardware"
- have "Show Hardware Details" be one of the options in the pop-up, than when selected shows the Toast with more details on the connected hardware

**Comment by andrewdavidmackenzie** [comment]
Let me know when done and add me for a code review (ping me on discord too). Thanks!

**Comment by andrewdavidmackenzie** [comment]
Is it possible to change the pointer cursor, when hovering over button, to suggest it is clickable?
I'm not sure, but it maybe did that before and not now?

**Comment by andrewdavidmackenzie** [comment]
Screenshot from 2024-07-09 20-32-19

Screenshot from 2024-07-09 20-32-29

Screenshot from 2024-07-09 20-32-39

**Comment by andrewdavidmackenzie** [comment]
I would also make clicking on the button again (the same as clicking to open it initially), to close the pop-up.

**Comment by andrewdavidmackenzie** [comment]
I just thought of this, so sorry for late requirements:

The two options:
- connect to remote pi
- search for pis on local network

should only show if you have built with the "networking" feature. But we can wait to merge my other networking PR that adds that feature flag, then come back in a new PR later from master (when both of these are merged) and do that correctly.

**Comment by sundaram123krishnan** [comment]
Fixed

**Comment by andrewdavidmackenzie** [comment]
That fixed the highlighting issue.
It still doesnt
- change mouse pointer on hover to show button is clickable
- close on button click

I think I preferred it without the border, or a much more subtler border...you?
Id try to make it look like an extension or outgrowth of the button itself, like the VS code, IntelliJ and other IDEs do....

**Comment by sundaram123krishnan** [comment]
Fixed the menu highlighting (shadow) and the border.
Will open new pr for these 2 changes:
- change mouse pointer on hover to show button is clickable
- close on button click

@andrewdavidmackenzie

**Comment by sundaram123krishnan** [comment]
To implement these two changes:

1. Change the mouse pointer on hover to indicate the button is clickable.
2. Close on button click.

I'll need to open a pull request in `iced_aw`.

**Review by andrewdavidmackenzie — APPROVED** [review]

**Comment by andrewdavidmackenzie** [comment]
Would be good if you linked the new issues you open here...for reference.

**Pull request merged**
